#!/usr/bin/env python3
"""Inline the supplied Material SVG icons with the desktop UI palette."""
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PALETTE = {"normal": "#7d8799", "accent": "#0071ff", "white": "#ffffff", "favorite": "#ffb900"}
icons = {}
for path in sorted((ROOT / "src/ui/icons").glob("*.svg")):
    source = path.read_text(encoding="utf-8")
    for variant, color in PALETTE.items():
        svg = source.replace("<svg ", f'<svg fill="{color}" ', 1)
        icons[f"{path.stem}_{variant}"] = "data:image/svg+xml;base64," + base64.b64encode(svg.encode()).decode()
(ROOT / "src/ui/icons.tis").write_text(
    "/* Generated by scripts/generate_sciter_icons.py; Material icons, Apache-2.0. See icons/NOTICE. */\n"
    + "const lanIcons = " + json.dumps(icons, indent=2) + ";\n"
    + 'function lanIcon(name, variant="normal") { return <img .icon src={lanIcons[name+"_"+variant] || lanIcons.desktop_normal} />; }\n',
    encoding="utf-8",
)
